export const CHARACTER_SOURCE = {
    goblin: {
        type: 'goblin',
        link: 'assets/chars/goblins/goblins.json',
    },
    boy: {
        type: 'boy',
        link: 'assets/chars//spineboy/spineboy.json',
    },
    dragon: {
        type: 'dragon',
        link: 'assets/chars/dragon/dragon.json',
    },
    pixie: {
        type: 'pixie',
        link: 'assets/chars/pixie/pixie.json',
    },
};

export const NAMES = [
    'Peter',
    'Meter',
    'Bob',
    'Rayan',
    'Jake',
    'Connor',
    'Callum',
    'Jacob',
    'Kyle',
    'Joe',
    'Reece',
    'Rhys',
    'Charlie',
    'Damian',
    'Oliver',
    'Jack',
    'Harry',
    'Charlie',
    'Thomas',
    'George',
    'Oscar',
    'James',
    'William',
    'Noah',
    'Liam',
    'Mason',
    'William',
    'Ethan',
    'Michael',
    'Alexander',
    'James',
    'Daniel',
    'James',
    'John',
    'Robert',
    'Joseph',
    'Charles',
    'Thomas',
];
